# Generated by Django 5.0.2 on 2024-04-23 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.place'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
