# Generated by Django 5.0.2 on 2024-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_meet_place_alter_meet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
