# Generated by Django 5.0.2 on 2024-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_meet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
